apiVersion: v1
kind: Service
metadata:
  name: ms-user-front
  labels:
    app: ms-user-front
spec:
  ports:
  - port: 80
  selector:
    app: ms-user-front
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-user-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-user-front
  template:
    metadata:
      labels:
        app: ms-user-front
    spec:
      containers:
      - name: ms-user-front
        image: angelolm/ms-user-front:latest
        ports:
        - containerPort: 80