apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: angelolm/unificado:latest
        ports:
        - containerPort: 4200

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80  
    targetPort: 4200 # El puerto externo sigue siendo 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-menurestaurant-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-menurestaurant
  template:
    metadata:
      labels:
        app: ms-menurestaurant
    spec:
      containers:
      - name: ms-menurestaurant
        image: pedroluyo/ms-menurestaurant:latest
        ports:
        - containerPort: 8086

---
apiVersion: v1
kind: Service
metadata:
  name: ms-menurestaurant-service
spec:
  type: LoadBalancer
  selector:
    app: ms-menurestaurant
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8086 # El puerto externo sigue siendo 80