apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: angelolm/unificado:latest
        ports:
        - containerPort: 4200

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80  
    targetPort: 4200 # El puerto externo sigue siendo 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-menurestaurant-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-menurestaurant
  template:
    metadata:
      labels:
        app: ms-menurestaurant
    spec:
      containers:
      - name: ms-menurestaurant
        image: pedroluyo/ms-menurestaurant:latest
        ports:
        - containerPort: 8086

---
apiVersion: v1
kind: Service
metadata:
  name: ms-menurestaurant-service
spec:
  type: LoadBalancer
  selector:
    app: ms-menurestaurant
  ports:
  - protocol: TCP
    port: 8086
    targetPort: 8086 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-letterplate-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-letterplate
  template:
    metadata:
      labels:
        app: ms-letterplate
    spec:
      containers:
      - name: ms-letterplate
        image: alexito03/ms-letterplate:latest
        ports:
        - containerPort: 9095
---
apiVersion: v1
kind: Service
metadata:
  name: ms-letterplate-service
spec:
  type: LoadBalancer
  selector:
    app: ms-letterplate
  ports:
  - protocol: TCP
    port: 9095  # Puerto externo del servicio
    targetPort: 9095  # Puerto del contenedor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-restaurant
  template:
    metadata:
      labels:
        app: ms-restaurant
    spec:
      containers:
      - name: ms-restaurant
        image: erickportuguez/ms-restaurant:latest
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: ms-restaurant-service
spec:
  type: LoadBalancer
  selector:
    app: ms-restaurant
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-menuplate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-menuplate
  template:
    metadata:
      labels:
        app: ms-menuplate
    spec:
      containers:
      - name: ms-menuplate
        image: naomicama/ms-menuplate:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ms-menuplate-service
spec:
  type: LoadBalancer
  selector:
    app: ms-menuplate
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    
